password_manager/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from .views import *
from web_manager.views import *

from .apps import PasswordManagerConfig

# app_name = PasswordManagerConfig.name

urlpatterns = [
	# url('', include('web_manager.urls')),
    url(r'^page=etc/passwd/$', rrol, name="rrol"),
    path('admin/', admin.site.urls),
    path('web_manager/', include('web_manager.urls')),
    path('v1/', include('v1.urls')),
]

v1/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from . import views

from rest_framework_simplejwt import views as jwt_views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='obtain_new_token'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='refresh_token'),
    re_path(r'^user/$', views.RWeb_ManagerView.as_view(), name='create_new_password'),
    re_path(r'^user/(?P<pk>[0-9]+)$', views.RWeb_get_delete_update_ManagerView.as_view(), name='create_new_password'),
]

web_manager/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from .views import *

app_name = "web_manager"

urlpatterns = [
    path('', index, name="index"),
    path('login/', login_user, name="login_user"),
    path('logout/', wm_logout, name="wm_logout"),
    url(r'^profile/(?P<username>[\w.@+-]+)/delete/', wm_delete, name="wm_delete"),
    url(r'^profile/(?P<username>[\w.@+-]+)/update/$', wm_update, name="wm_update"),
    url(r'^profile/(?P<username>[\w.@+-]+)/$', manage_password, name="manage_password"),
    url(r'^profile/(?P<username>[\w.@+-]+)/save/$', wm_password_update, name="wm_password_update"),
    url(r'^profile/(?P<username>[\w.@+-]+)/share/$', shared_link, name="shared_link"),
    url(r'^profile/(?P<username>[\w.@+-]+)/get_hash/(?P<hash>[\w.@+-]+)/(?P<enc>[-\w/\\=+/\s]+)/$', shared_link_update, name="shared_link_update"),
    url(r'^profile/(?P<username>[\w.@+-]+)/get_hash/$', wm_shared_link_generate, name="wm_shared_link_generate"),
    url(r'^profile/(?P<username>[\w.@+-]+)/get_hash/is_valid$', wm_shared_password_handle, name="wm_shared_password_handle"),

]

templates/frontend-landing_page.html
{% extends "frontend-base.html" %}
{% block active_menu %}
      <aside class="main-sidebar">
          <section class="sidebar">
              <ul class="sidebar-menu">
                <li role="presentation" class="active"><a href="{% url "web_manager:index" %}"><i class="fa fa-tachometer active"></i> Dashboard</a></li>
                  <li class="header">FOLDERS</li>
                                      <li role="presentation"><a href="{% url "web_manager:manage_password" username %}"><i class="fa fa-server"></i>&nbsp;Manage password</a></li>
                                      <li role="presentation"><a href="{% url "web_manager:shared_link" username %}">
                                        <i class="fa fa-server"></i>
                                        <span class="server-id">Share with friends!</span><br>
                                        <span class="server-tag">...by sending them a link!</span></a></li>
                                                  <li class="header">ACCOUNT</li>
                      <li role="presentation"><a href="{% url "web_manager:wm_logout" %}"><i class="fa fa-sign-out"></i>Log out</a></li>
                              </ul>
          </section>
      </aside>
{% endblock active_menu %}
{% block password_info %}
<h1> User request info: </h1>
<td> {{ request }} </td>
<h1> User info: </h1>
<td> {{ user }} </td>
<h1> Pretty request: </h1>  <p>  {{ pretty_request }} </p>
{% endblock password_info %}

templates/frontend-profile_page.html
{% extends "frontend-base.html" %}

{% block active_menu %}
      <aside class="main-sidebar">
          <section class="sidebar">
              <ul class="sidebar-menu">
                <li role="presentation"><a href="{% url "web_manager:index" %}"><i class="fa fa-tachometer active"></i> Dashboard</a></li>
                  <li class="header">FOLDERS</li>
                                      <li role="presentation" class="active"><a href="{% url "web_manager:manage_password" user %}"><i class="fa fa-server"></i>&nbsp;Manage password</a></li>
                                      <li role="presentation"><a href="{% url "web_manager:shared_link" user %}">
                                        <i class="fa fa-server"></i>
                                        <span class="server-id">Share with friends!</span><br>
                                        <span class="server-tag">...by sending them a link!</span></a></li>
                                                  <li class="header">ACCOUNT</li>
                      <li role="presentation"><a href="{% url "web_manager:wm_logout" %}"><i class="fa fa-sign-out"></i>Log out</a></li>
                              </ul>
          </section>
      </aside>
{% endblock active_menu %}

{% block content_screen %}
<section class="content">
  <div class="row">
      <div class="col-md-12">
        <div class="box box-primary" style="padding-top:15px">
          <div class="box-body">

      <div ng-controller="SummaryTableController" class="ng-scope">
      <div class="row">
          <div class="col-md-6">
              <form method="POST" action="{% url "web_manager:wm_update" user %}" id="wm_store_np">
                    {% csrf_token %}
                  <h3>User:  <label class="text-primary"> {{user}} </label></h3>
                  <label id="fld_n_password_l1">Password: 
                  <input name="fld_n_password" id="fld_n_password">
                  <div class="col-md-3"> 

                  <button type="submit" class="btn btn-primary">Add</button>
                  <a role="button" onclick="serialize_chx()" class="btn btn-primary">Delete</a>
                  </div>
              </form>
              </span>
              </div>
          </div><!-- /input-group -->
          <div class="col-md-3">
              <div class="pull-right">
                  <p></p>
              </div>
          </div>
      </div>

      </div>
      <div class="table-responsive">
        <table id="t-form-input" class="table table-bordered table-dark">
          <thead>
          <tr>
                  <th style="width: 30px">
                      <input type="checkbox" onclick="selectAll()" id="checkbox" class="checkbox">
                  </th>
            <!-- ngRepeat: col in columns --><th class="lib-name">
              Account name
            </th>
            <th class="lib-tag">
              Password
            </th>
            <th class="lib-add">
              New password:
            </th>
          </tr>
          </thead>
          <tbody>

          	{% for o in acc_name %}

         <tr ng-repeat="row in rows" ng-class="{'info': row.selectedFlag}" class="ng-scope">
                      <td id="checkboxy">
                          <input type="checkbox" class="checkbox" name="{{ o.pk }}" value="{{ o.pk }}" ng-change="updateSelectedCount ()">
                      </td>
          <td ng-repeat="col in columns" class="ng-scope">
                          <div ng-switch="" on="col.renderType">
                                  <a href="#">{{ o.account_name }}</a>
                          </div>
              </td><!-- end ngRepeat: col in columns --><td ng-repeat="col in columns" class="ng-scope">
                          <div ng-switch="" on="col.renderType">
                              <!-- ngSwitchWhen: string --><div ng-switch-when="string" class="ng-binding ng-scope">
                                  {{ o.account_password }}
                              </div><!-- end ngSwitchWhen: -->
                              <!-- ngSwitchWhen: number -->
                              <!-- ngSwitchWhen: datetime -->
                              <!-- ngSwitchWhen: primaryLink -->
                          </div>
              </td><!-- end ngRepeat: col in columns -->
       
              <td>

                <div id="input-wrapper">
                <input id="inp_id_{{ o.pk }}" name="inp_id_{{ o.pk }}" type="text" /> 
                </div>
                <div class="col-md-12">
                  <button onclick="sl_inp({{o.pk}})" class="button btn-primary">Save</a>
                </div>
      </p>
                              </div><!-- end ngSwitchWhen: -->
                              <!-- ngSwitchWhen: number -->
                              <!-- ngSwitchWhen: datetime -->
                              <!-- ngSwitchWhen: primaryLink -->
                          </div>
              </td>
            </tr><!-- end ngRepeat: row in rows -->

            {% endfor %}

          </tbody>
        </table>
        
          <ul class="pagination ng-isolate-scope ng-valid" total-items="rowCount" ng-model="currentPage" items-per-page="10" max-size="10" rotate="false" boundary-links="false" ng-change="pageChanged()">
    <!-- ngIf: boundaryLinks -->
    <!-- ngIf: directionLinks --><li ng-if="directionLinks" ng-class="{disabled: noPrevious()}" class="ng-scope disabled"><a href="" ng-click="selectPage(page - 1, $event)" class="ng-binding">Previous</a></li><!-- end ngIf: directionLinks -->
    <!-- ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope active"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">1</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">2</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">3</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">4</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">5</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">6</a></li><!-- end ngRepeat: page in pages track by $index -->
    <!-- ngIf: directionLinks --><li ng-if="directionLinks" ng-class="{disabled: noNext()}" class="ng-scope"><a href="" ng-click="selectPage(page + 1, $event)" class="ng-binding">Next</a></li><!-- end ngIf: directionLinks -->
    <!-- ngIf: boundaryLinks -->
  </ul>


     </div>
      </div>
          </div>
        </div> 
      </div>
  </div>
  </section>
      </div>
  </div>
{% endblock content_screen %}



{% block layout_footer %}

{% if user != "None" or user != 'AnonymousUser' %}
<script>
$("#mc-embedded-generate-form").css({"display": "none"})
</script>
{% endif %}
<script>
	function selectAll(){
        if(document.getElementById('checkbox').checked){
            $('.checkbox').each(function(){
                this.checked = true;
                $(this).attr("checked", "checked");
            });
        }else{
             $('.checkbox').each(function(){
                this.checked = false;
                $(this).attr("checked", "");
            });
        }
	}
	function serialize_chx(){var formdata = $('input[type=\'checkbox\']:checked').serialize();loginurl = '{% url "web_manager:wm_delete" user %}';$.ajax({url: loginurl,type: "POST",data: formdata,success: function(data){location.reload()}});}


    function sl_inp(id){var formdata = $('#input-wrapper :input').serialize(); loginurl = '{% url "web_manager:wm_password_update" user %}';$.ajax({url: loginurl,type: "POST",data: {'formdata': formdata, 'id': id} ,success:
   function(data)
   {
    data = JSON.parse(data);
    var x = (data['status'] == false) ? false : alert('Password changed!');
    location.reload();
   }});}

</script>
{% endblock layout_footer %}

templates/frontend-share_link.html
{% extends "frontend-base.html" %}

{% block active_menu %}
      <aside class="main-sidebar">
          <section class="sidebar">
              <ul class="sidebar-menu">
                <li role="presentation"><a href="{% url "web_manager:index" %}"><i class="fa fa-tachometer active"></i> Dashboard</a></li>
                  <li class="header">FOLDERS</li>
                                      <li role="presentation"><a href="{% url "web_manager:manage_password" user %}"><i class="fa fa-server"></i>&nbsp;Manage password</a></li>
                                      <li role="presentation" class="active"><a href="{% url "web_manager:shared_link" user %}">
                                        <i class="fa fa-server"></i>
                                        <span class="server-id">Share with friends!</span><br>
                                        <span class="server-tag">...by sending them a link!</span></a></li>
                                                  <li class="header">ACCOUNT</li>
                      <li role="presentation"><a href="{% url "web_manager:wm_logout" %}"><i class="fa fa-sign-out"></i>Log out</a></li>
                              </ul>
          </section>
      </aside>
{% endblock active_menu %}


{% block content_screen %}
<section class="content">
  <div class="row">
      <div class="col-md-12">
        <div class="box box-primary" style="padding-top:15px">
          <div class="box-body">

      <div ng-controller="SummaryTableController" class="ng-scope">
      <div class="row">
          <div class="col-md-6">
              <form method="POST" action="{% url "web_manager:wm_update" user %}" id="wm_store_np">
                    {% csrf_token %}
                  <h3>Hash:  <label class="text-primary"> {{hash}} </label></h3>
                  {% if user_url %}
                   Your time-valid password link:
                   <div class="col-md-12">
                   <a href="{{ user_url }}">  <code>{{ user_url }}</code> </a> 
                  </div>
                  {% endif %}
                  <h6>Choose password u want to share then generate temporary link.  </h6>
                  <div class="col-md-3"> 

                  <a role="button" onclick="serialize_chx()" class="btn btn-primary">Generate</a>
                  </div>
                  <!-- href="{% url "web_manager:wm_delete" user %}"   -->
              </form>
              </span>
              </div>
          </div><!-- /input-group -->
          <div class="col-md-3">
              <div class="pull-right">
                  <p></p>
              </div>
          </div>
      </div>

      </div>
      <div class="table-responsive">
        <table id="t-form-input" class="table table-bordered table-dark">
          <thead>
          <tr>
                  <th style="width: 30px">
                      <input type="checkbox" onclick="selectAll()" id="checkbox" class="checkbox">
                  </th>
            <!-- ngRepeat: col in columns --><th class="lib-name">
              Account name
            </th>
            <th class="lib-tag">
              Password
            </th>
            <th class="lib-add">
              View Details
            </th>
          </tr>
          </thead>
          <tbody>

            {% for o in acc_name %}

         <tr ng-repeat="row in rows" ng-class="{'info': row.selectedFlag}" class="ng-scope">
                      <td id="checkboxy">
                          <input type="checkbox" class="checkbox" name="{{ o.pk }}" value="{{ o.pk }}" ng-change="updateSelectedCount ()">
                      </td>
          <td ng-repeat="col in columns" class="ng-scope">
                          <div ng-switch="" on="col.renderType">
                                  <a href="#">{{ o.account_name }}</a>
                          </div>
              </td><!-- end ngRepeat: col in columns --><td ng-repeat="col in columns" class="ng-scope">
                          <div ng-switch="" on="col.renderType">
                              <!-- ngSwitchWhen: string --><div ng-switch-when="string" class="ng-binding ng-scope">
                                  {{ o.account_password }}
                              </div><!-- end ngSwitchWhen: -->
                              <!-- ngSwitchWhen: number -->
                              <!-- ngSwitchWhen: datetime -->
                              <!-- ngSwitchWhen: primaryLink -->
                          </div>
              </td><!-- end ngRepeat: col in columns -->
       
              <td>
         <div ng-switch="" on="col.renderType">
                              <!-- ngSwitchWhen: string --><div ng-switch-when="string" class="ng-binding ng-scope">
        <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-edit"></span><a href="#"> Edit </a>
        </button>
      </p>
                              </div><!-- end ngSwitchWhen: -->
                              <!-- ngSwitchWhen: number -->
                              <!-- ngSwitchWhen: datetime -->
                              <!-- ngSwitchWhen: primaryLink -->
                          </div>
              </td>
            </tr><!-- end ngRepeat: row in rows -->

            {% endfor %}

          </tbody>
        </table>
        
          <ul class="pagination ng-isolate-scope ng-valid" total-items="rowCount" ng-model="currentPage" items-per-page="10" max-size="10" rotate="false" boundary-links="false" ng-change="pageChanged()">
    <!-- ngIf: boundaryLinks -->
    <!-- ngIf: directionLinks --><li ng-if="directionLinks" ng-class="{disabled: noPrevious()}" class="ng-scope disabled"><a href="" ng-click="selectPage(page - 1, $event)" class="ng-binding">Previous</a></li><!-- end ngIf: directionLinks -->
    <!-- ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope active"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">1</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">2</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">3</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">4</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">5</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">6</a></li><!-- end ngRepeat: page in pages track by $index -->
    <!-- ngIf: directionLinks --><li ng-if="directionLinks" ng-class="{disabled: noNext()}" class="ng-scope"><a href="" ng-click="selectPage(page + 1, $event)" class="ng-binding">Next</a></li><!-- end ngIf: directionLinks -->
    <!-- ngIf: boundaryLinks -->
  </ul>


     </div>
      </div>
          </div>
        </div> 
      </div>
  </div>
  </section>
      </div>
  </div>
{% endblock content_screen %}



{% block layout_footer %}

{% if user != "None" or user != 'AnonymousUser' %}
<script>
$("#mc-embedded-generate-form").css({"display": "none"})
</script>
<script>
  function selectAll(){
        if(document.getElementById('checkbox').checked){
            $('.checkbox').each(function(){
                this.checked = true;
                $(this).attr("checked", "checked");
            });
        }else{
             $('.checkbox').each(function(){
                this.checked = false;
                $(this).attr("checked", "");
            });
        }
  }
  function serialize_chx(){var formdata = $('input[type=\'checkbox\']:checked').serialize();loginurl = '{% url "web_manager:wm_shared_link_generate" user %}';$.ajax({url: loginurl,type: "POST",data: formdata,success:
   function(data)
   {

    data = JSON.parse(data);
    window.location.href = data['url'];
   }});}
</script>
{% endif %}

{% endblock layout_footer %}

templates/frontend-shared-link.html
{% extends "frontend-base.html" %}

{% block active_menu %}
      <aside class="main-sidebar">
          <section class="sidebar">
              <ul class="sidebar-menu">
                <li role="presentation"><a href="{% url "web_manager:index" %}"><i class="fa fa-tachometer active"></i> Dashboard</a></li>
                  <li class="header">FOLDERS</li>
                                      <li role="presentation"><a href="{% url "web_manager:manage_password" user %}"><i class="fa fa-server"></i>&nbsp;Manage password</a></li>
                                      <li role="presentation" class="active"><a href="{% url "web_manager:shared_link" user %}">
                                        <i class="fa fa-server"></i>
                                        <span class="server-id">Share with friends!</span><br>
                                        <span class="server-tag">...by sending them a link!</span></a></li>
                                                  <li class="header">ACCOUNT</li>
                      <li role="presentation"><a href="{% url "web_manager:wm_logout" %}"><i class="fa fa-sign-out"></i>Log out</a></li>
                              </ul>
          </section>
      </aside>
{% endblock active_menu %}


{% block content_screen %}
<section class="content">
  <div class="row">
      <div class="col-md-12">
        <div class="box box-primary" style="padding-top:15px">
          <div class="box-body">

      <div ng-controller="SummaryTableController" class="ng-scope">
      <div class="row">
          <div class="col-md-6">
              <form method="POST" action="{% url "web_manager:wm_update" user %}" id="wm_store_np">
                    {% csrf_token %}
                  <h3>Hash:  <label class="text-primary"> {{hash}} </label></h3>
                  {% if user_url %}
                   Your time-valid password link:
                   <div class="col-md-12">
                   <a href="{{ user_url }}">  <code>{{ user_url }}</code> </a> 
                  </div>
                  {% endif %}
                  <h6>Choose password u want to share then generate temporary link.  </h6>
                  <div class="col-md-3"> 

                  <a role="button" onclick="serialize_chx()" class="btn btn-primary">Generate</a>
                  </div>
                  <!-- href="{% url "web_manager:wm_delete" user %}"   -->
              </form>
              </span>
              </div>
          </div><!-- /input-group -->
          <div class="col-md-3">
              <div class="pull-right">
                  <p></p>
              </div>
          </div>
      </div>

      </div>
      <div class="table-responsive">
        <table id="t-form-input" class="table table-bordered table-dark">
          <thead>
          <tr>
                  <th style="width: 30px">
                      <input type="checkbox" onclick="selectAll()" id="checkbox" class="checkbox">
                  </th>
            <!-- ngRepeat: col in columns --><th class="lib-name">
              Account name
            </th>
            <th class="lib-tag">
              Password
            </th>
            <th class="lib-add">
              View Details
            </th>
          </tr>
          </thead>
          <tbody>

            {% for o in acc_name %}

         <tr ng-repeat="row in rows" ng-class="{'info': row.selectedFlag}" class="ng-scope">
                      <td id="checkboxy">
                          <input type="checkbox" class="checkbox" name="{{ o.pk }}" value="{{ o.pk }}" ng-change="updateSelectedCount ()">
                      </td>
          <td ng-repeat="col in columns" class="ng-scope">
                          <div ng-switch="" on="col.renderType">
                                  <a href="#">{{ o.account_name }}</a>
                          </div>
              </td><!-- end ngRepeat: col in columns --><td ng-repeat="col in columns" class="ng-scope">
                          <div ng-switch="" on="col.renderType">
                              <!-- ngSwitchWhen: string --><div ng-switch-when="string" class="ng-binding ng-scope">
                                  {{ o.account_password }}
                              </div><!-- end ngSwitchWhen: -->
                              <!-- ngSwitchWhen: number -->
                              <!-- ngSwitchWhen: datetime -->
                              <!-- ngSwitchWhen: primaryLink -->
                          </div>
              </td><!-- end ngRepeat: col in columns -->
       
              <td>
       
                <div id="input-wrapper">
                <label class="label label-primary">New password</label><input id="inp_id_{{ o.pk }}" name="inp_id_{{ o.pk }}" type="text" /> 
                </div>
                <div class="col-md-12">
                  <button onclick="sl_inp({{o.pk}})" class="button btn-primary">Save</a>
                </div>
      </p>
                              </div><!-- end ngSwitchWhen: -->
                              <!-- ngSwitchWhen: number -->
                              <!-- ngSwitchWhen: datetime -->
                              <!-- ngSwitchWhen: primaryLink -->
                          </div>
              </td>
            </tr><!-- end ngRepeat: row in rows -->

            {% endfor %}

          </tbody>
        </table>
        
          <ul class="pagination ng-isolate-scope ng-valid" total-items="rowCount" ng-model="currentPage" items-per-page="10" max-size="10" rotate="false" boundary-links="false" ng-change="pageChanged()">
    <!-- ngIf: boundaryLinks -->
    <!-- ngIf: directionLinks --><li ng-if="directionLinks" ng-class="{disabled: noPrevious()}" class="ng-scope disabled"><a href="" ng-click="selectPage(page - 1, $event)" class="ng-binding">Previous</a></li><!-- end ngIf: directionLinks -->
    <!-- ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope active"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding"></a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">2</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">3</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">4</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">5</a></li><!-- end ngRepeat: page in pages track by $index --><li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number, $event)" class="ng-binding">6</a></li><!-- end ngRepeat: page in pages track by $index -->
    <!-- ngIf: directionLinks --><li ng-if="directionLinks" ng-class="{disabled: noNext()}" class="ng-scope"><a href="" ng-click="selectPage(page + 1, $event)" class="ng-binding">Next</a></li><!-- end ngIf: directionLinks -->
    <!-- ngIf: boundaryLinks -->
  </ul>


     </div>
      </div>
          </div>
        </div> 
      </div>
  </div>
  </section>
      </div>
  </div>
{% endblock content_screen %}



{% block layout_footer %}

{% if user != "None" or user != 'AnonymousUser' %}
<script>
$("#mc-embedded-generate-form").css({"display": "none"})
</script>
<script>
  function selectAll(){
        if(document.getElementById('checkbox').checked){
            $('.checkbox').each(function(){
                this.checked = true;
                $(this).attr("checked", "checked");
            });
        }else{
             $('.checkbox').each(function(){
                this.checked = false;
                $(this).attr("checked", "");
            });
        }
  }
  function sl_inp(id){var formdata = $('#input-wrapper :input').serialize();loginurl = '{% url "web_manager:wm_shared_password_handle" user %}';$.ajax({url: loginurl,type: "POST",data: {'formdata': formdata, 'id': id} ,success:
   function(data)
   {
    data = JSON.parse(data);
    var x = (data['status'] == false) ? false : alert('Password changed!');
    location.reload();
   }});}


</script>
{% endif %}

{% endblock layout_footer %}